apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app: api 
    spec:
        containers:
        - name: api 
          image: us.gcr.io/fomo-204904/api:dev
          imagePullPolicy: Always 
          command: [
            "./api",
            "--selector=static"
          ]
          envFrom:
          - configMapRef:
              name: fomo-config
          env:
          - name: UPDATED_AT
            value: "Fri Oct  5 15:26:34 MDT 2018"
          ports:
          - containerPort:  443 
            name: https-port
          - containerPort:  80 
            name: http-port
          volumeMounts:
          - mountPath: /mnt/fomo
            name: api-data
        volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: fomo-stage-api-vol 
