apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app: api 
    spec:
        containers:
        - name: api 
          image: dockerowy/oldiez-api:dev 
          imagePullPolicy: Always 
          command: [
            "./api",
            "--selector=static"
          ]
          envFrom:
          - configMapRef:
              name: oldiez-config
          env:
          - name: UPDATED_AT
            value: "Sun Dec  9 20:33:39 MST 2018"
          ports:
          - containerPort: 9000
            name: http-port
