apiVersion: v1
kind: Service
metadata:
  name: api 
  labels:
    app: api 
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5000 
    targetPort: 9000
    nodePort: 30000
  selector:
    app: api 