apiVersion: v1
kind: Service
metadata:
  name: api 
  labels:
    app: api 
spec:
  type: LoadBalancer
  loadBalancerIP: "localhost"
  ports:
  - name: http
    protocol: TCP
    port: 9000 
    targetPort: 9000 
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443 
  selector:
    app: api 