// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package apiql

type NewLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Remember bool   `json:"remember"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Token struct {
	Jwt     *string `json:"jwt"`
	Refresh *string `json:"refresh"`
}
