apiVersion: v1
kind: ConfigMap
metadata:
  name: fomo-config
data:
  DB_URL: postgres://postgres@postgres/fomo_stage?sslmode=disable
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_USER: postgres