apiVersion: apps/v1 
kind: Deployment
metadata:
  namespace: default
  name: api-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-graphql 
  template:
    metadata:
      labels:
        app: api-graphql 
    spec:
        containers:
        - name: api-graphql 
          image: dockerowy/appa-apiql:dev 
          imagePullPolicy: Always 
          envFrom:
          - configMapRef:
              name: api-graphql-config 
          env:
          - name: UPDATED_AT
            value: "Mon May 18 20:46:05 MDT 2020"
          ports:
          - containerPort: 8080 
            name: http-port
