apiVersion: v1
kind: Service
metadata:
  name: api-graphql 
  labels:
    app: api-graphql 
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8080 
    targetPort: 8080
    nodePort: 30000
  selector:
    app: api-graphql 