# docker-compose.yml
version: '3.6'

services:

  api:
    build: ./api
  
  balance-service:
    build: ./balance-service

  binance-service: 
    build: ./binance-service

  binance-websocket: 
    build: ./binance-websocket

  bittrex-service:
    build: ./bittrex-service

  device-service:
    build: ./device-service

  execution-engine:
    build: ./execution-engine

  key-service:
    build: ./key-service

  order-service:
    build: ./order-service

  user-service:
    build: ./user-service

  database:
    image: postgres
  
  gorush:
    image: appleboy/gorush
