# docker-compose.yml
version: '3.1'

services:

  api:
    build: ./api
    ports: 
      - 5000:5000
    environment:
      DB_URL: "postgres://postgres@docker.for.mac.host.internal:5432/gomo_dev?&sslmode=disable"
      MICRO_SERVER_ADDRESS: ":5001"
      MICRO_REGISTRY: "mdns"
      GOMO_JWT: "jyVadHV5Z+tihp4ptuEvD2xXu6iWrFaSebYovtmzl0Cg4RDi1udp7qyme8ZZQl+A"

  user-service:
    build: ./user-service
    ports:
      - 5001:5001
    environment:
      DB_URL: "postgres://postgres@docker.for.mac.host.internal:5432/gomo_dev?&sslmode=disable"
      MICRO_ADDRESS: ":5001"
      MICRO_REGISTRY: "mdns"
