// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/story/story.proto

/*
Package story is a generated protocol buffer package.

It is generated from these files:
	proto/story/story.proto

It has these top-level messages:
	NewStoryRequest
	Story
	StoryData
	StoryResponse
*/
package story

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StoryService service

type StoryService interface {
	NewStory(ctx context.Context, in *NewStoryRequest, opts ...client.CallOption) (*StoryResponse, error)
}

type storyService struct {
	c    client.Client
	name string
}

func NewStoryService(name string, c client.Client) StoryService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "storyservice"
	}
	return &storyService{
		c:    c,
		name: name,
	}
}

func (c *storyService) NewStory(ctx context.Context, in *NewStoryRequest, opts ...client.CallOption) (*StoryResponse, error) {
	req := c.c.NewRequest(c.name, "StoryService.NewStory", in)
	out := new(StoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StoryService service

type StoryServiceHandler interface {
	NewStory(context.Context, *NewStoryRequest, *StoryResponse) error
}

func RegisterStoryServiceHandler(s server.Server, hdlr StoryServiceHandler, opts ...server.HandlerOption) error {
	type storyService interface {
		NewStory(ctx context.Context, in *NewStoryRequest, out *StoryResponse) error
	}
	type StoryService struct {
		storyService
	}
	h := &storyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StoryService{h}, opts...))
}

type storyServiceHandler struct {
	StoryServiceHandler
}

func (h *storyServiceHandler) NewStory(ctx context.Context, in *NewStoryRequest, out *StoryResponse) error {
	return h.StoryServiceHandler.NewStory(ctx, in, out)
}
