// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/story/story.proto

package story

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Requests
type InitStoryRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserEmail            string   `protobuf:"bytes,3,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Rated                float64  `protobuf:"fixed64,6,opt,name=rated,proto3" json:"rated,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitStoryRequest) Reset()         { *m = InitStoryRequest{} }
func (m *InitStoryRequest) String() string { return proto.CompactTextString(m) }
func (*InitStoryRequest) ProtoMessage()    {}
func (*InitStoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c3a047a85f5b524, []int{0}
}

func (m *InitStoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitStoryRequest.Unmarshal(m, b)
}
func (m *InitStoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitStoryRequest.Marshal(b, m, deterministic)
}
func (m *InitStoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitStoryRequest.Merge(m, src)
}
func (m *InitStoryRequest) XXX_Size() int {
	return xxx_messageInfo_InitStoryRequest.Size(m)
}
func (m *InitStoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitStoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitStoryRequest proto.InternalMessageInfo

func (m *InitStoryRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *InitStoryRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InitStoryRequest) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *InitStoryRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *InitStoryRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *InitStoryRequest) GetRated() float64 {
	if m != nil {
		return m.Rated
	}
	return 0
}

func (m *InitStoryRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteStoryRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStoryRequest) Reset()         { *m = DeleteStoryRequest{} }
func (m *DeleteStoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStoryRequest) ProtoMessage()    {}
func (*DeleteStoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c3a047a85f5b524, []int{1}
}

func (m *DeleteStoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStoryRequest.Unmarshal(m, b)
}
func (m *DeleteStoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStoryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStoryRequest.Merge(m, src)
}
func (m *DeleteStoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStoryRequest.Size(m)
}
func (m *DeleteStoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStoryRequest proto.InternalMessageInfo

func (m *DeleteStoryRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeleteStoryRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// Responses
type Story struct {
	StoryID              string   `protobuf:"bytes,1,opt,name=storyID,proto3" json:"storyID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Rated                float64  `protobuf:"fixed64,5,opt,name=rated,proto3" json:"rated,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedOn            string   `protobuf:"bytes,10,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	UpdatedOn            string   `protobuf:"bytes,11,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Story) Reset()         { *m = Story{} }
func (m *Story) String() string { return proto.CompactTextString(m) }
func (*Story) ProtoMessage()    {}
func (*Story) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c3a047a85f5b524, []int{2}
}

func (m *Story) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Story.Unmarshal(m, b)
}
func (m *Story) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Story.Marshal(b, m, deterministic)
}
func (m *Story) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Story.Merge(m, src)
}
func (m *Story) XXX_Size() int {
	return xxx_messageInfo_Story.Size(m)
}
func (m *Story) XXX_DiscardUnknown() {
	xxx_messageInfo_Story.DiscardUnknown(m)
}

var xxx_messageInfo_Story proto.InternalMessageInfo

func (m *Story) GetStoryID() string {
	if m != nil {
		return m.StoryID
	}
	return ""
}

func (m *Story) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Story) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Story) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Story) GetRated() float64 {
	if m != nil {
		return m.Rated
	}
	return 0
}

func (m *Story) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Story) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Story) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

type StoryData struct {
	Story                *Story   `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoryData) Reset()         { *m = StoryData{} }
func (m *StoryData) String() string { return proto.CompactTextString(m) }
func (*StoryData) ProtoMessage()    {}
func (*StoryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c3a047a85f5b524, []int{3}
}

func (m *StoryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoryData.Unmarshal(m, b)
}
func (m *StoryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoryData.Marshal(b, m, deterministic)
}
func (m *StoryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoryData.Merge(m, src)
}
func (m *StoryData) XXX_Size() int {
	return xxx_messageInfo_StoryData.Size(m)
}
func (m *StoryData) XXX_DiscardUnknown() {
	xxx_messageInfo_StoryData.DiscardUnknown(m)
}

var xxx_messageInfo_StoryData proto.InternalMessageInfo

func (m *StoryData) GetStory() *Story {
	if m != nil {
		return m.Story
	}
	return nil
}

type StoryResponse struct {
	Status               string     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *StoryData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StoryResponse) Reset()         { *m = StoryResponse{} }
func (m *StoryResponse) String() string { return proto.CompactTextString(m) }
func (*StoryResponse) ProtoMessage()    {}
func (*StoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c3a047a85f5b524, []int{4}
}

func (m *StoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoryResponse.Unmarshal(m, b)
}
func (m *StoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoryResponse.Marshal(b, m, deterministic)
}
func (m *StoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoryResponse.Merge(m, src)
}
func (m *StoryResponse) XXX_Size() int {
	return xxx_messageInfo_StoryResponse.Size(m)
}
func (m *StoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoryResponse proto.InternalMessageInfo

func (m *StoryResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StoryResponse) GetData() *StoryData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*InitStoryRequest)(nil), "InitStoryRequest")
	proto.RegisterType((*DeleteStoryRequest)(nil), "DeleteStoryRequest")
	proto.RegisterType((*Story)(nil), "Story")
	proto.RegisterType((*StoryData)(nil), "StoryData")
	proto.RegisterType((*StoryResponse)(nil), "StoryResponse")
}

func init() { proto.RegisterFile("proto/story/story.proto", fileDescriptor_5c3a047a85f5b524) }

var fileDescriptor_5c3a047a85f5b524 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xd1, 0x4e, 0xea, 0x40,
	0x10, 0xbd, 0x0b, 0xb4, 0xd0, 0xe9, 0xd5, 0xe8, 0x6a, 0x74, 0x43, 0x88, 0x21, 0x7d, 0xc2, 0x97,
	0x6a, 0xd0, 0x2f, 0x30, 0xf8, 0xc0, 0x93, 0x49, 0xf9, 0x82, 0x15, 0x26, 0xa6, 0x09, 0xb4, 0xd8,
	0x1d, 0x48, 0xfc, 0x3d, 0x7f, 0xc1, 0x1f, 0x32, 0x3b, 0xdb, 0xd6, 0x22, 0x90, 0xf8, 0xd2, 0xec,
	0x39, 0xb3, 0xb3, 0x3d, 0xe7, 0xcc, 0xc0, 0xf5, 0xba, 0xc8, 0x29, 0xbf, 0x33, 0x94, 0x17, 0x1f,
	0xee, 0x1b, 0x33, 0x13, 0x7d, 0x0a, 0x38, 0x9b, 0x66, 0x29, 0xcd, 0x2c, 0x97, 0xe0, 0xfb, 0x06,
	0x0d, 0xc9, 0x2b, 0xf0, 0x37, 0x06, 0x8b, 0xe9, 0x44, 0x89, 0xa1, 0x18, 0x05, 0x49, 0x89, 0x64,
	0x1f, 0x7a, 0xf6, 0x94, 0xe9, 0x15, 0xaa, 0x16, 0x57, 0x6a, 0x2c, 0x07, 0x10, 0xd8, 0xf3, 0xf3,
	0x4a, 0xa7, 0x4b, 0xd5, 0xe6, 0xe2, 0x0f, 0x21, 0x2f, 0xc1, 0xa3, 0x94, 0x96, 0xa8, 0x3a, 0x5c,
	0x71, 0x40, 0x2a, 0xe8, 0xce, 0xf3, 0x8c, 0x30, 0x23, 0xe5, 0x31, 0x5f, 0x41, 0x7b, 0xbf, 0xd0,
	0x84, 0x0b, 0xe5, 0x0f, 0xc5, 0x48, 0x24, 0x0e, 0x58, 0x5d, 0x86, 0x34, 0x6d, 0x8c, 0xea, 0x3a,
	0x5d, 0x0e, 0x45, 0x4f, 0x20, 0x27, 0xb8, 0x44, 0xc2, 0x3f, 0xb9, 0xa8, 0xb5, 0xb4, 0x1a, 0x5a,
	0xa2, 0x2f, 0x01, 0x1e, 0xb7, 0x5b, 0x55, 0x9c, 0x50, 0xdd, 0x58, 0xc1, 0xc6, 0x8b, 0xad, 0xc3,
	0x2f, 0xb6, 0x8f, 0xb8, 0xeb, 0x1c, 0x71, 0xe7, 0x1d, 0x76, 0xd7, 0x6b, 0xba, 0xb3, 0xc9, 0xce,
	0x0b, 0xb4, 0x57, 0x5e, 0x32, 0x05, 0x2e, 0xd9, 0x9a, 0xe0, 0xdc, 0xd7, 0x8b, 0xb2, 0x1a, 0x96,
	0xb9, 0x57, 0x44, 0x74, 0x0b, 0x01, 0x9b, 0x9a, 0x68, 0xd2, 0x72, 0x00, 0x1e, 0x3b, 0x61, 0x5b,
	0xe1, 0xd8, 0x8f, 0x5d, 0x5c, 0x8e, 0x8c, 0x34, 0x9c, 0x94, 0xf1, 0x99, 0x75, 0x9e, 0x19, 0x6c,
	0xe8, 0x11, 0x3b, 0x7a, 0x14, 0x74, 0x57, 0x68, 0x8c, 0x7e, 0xab, 0x12, 0xac, 0xa0, 0xbc, 0x81,
	0xce, 0x42, 0x93, 0xe6, 0x18, 0xc2, 0x31, 0xc4, 0xf5, 0xaf, 0x13, 0xe6, 0xc7, 0x5b, 0xf8, 0xcf,
	0xd4, 0x0c, 0x8b, 0x6d, 0x3a, 0x47, 0x79, 0x0f, 0x41, 0xbd, 0x7b, 0xf2, 0x3c, 0xfe, 0xbd, 0x87,
	0xfd, 0xd3, 0x78, 0x47, 0x51, 0xf4, 0x4f, 0x3e, 0x42, 0xd8, 0x98, 0xb4, 0xbc, 0x88, 0xf7, 0xe7,
	0xbe, 0xdf, 0xf5, 0xea, 0xf3, 0xae, 0x3f, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x11, 0xc5,
	0x74, 0x06, 0x03, 0x00, 0x00,
}
