kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fomo-stage-swagger-vol 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 