apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: devices 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devices 
  template:
    metadata:
      labels:
        app: devices 
    spec:
        containers:
        - name: device-service 
          image: us.gcr.io/fomo-204904/device-service:dev
          imagePullPolicy: Always 
          command: [
            "./device-service",
            "--selector=static",
            "--server_address=:8080"
          ]
          envFrom:
          - configMapRef:
              name: fomo-config
          env:
          - name: UPDATED_AT
            value: "Sat Jul 28 18:59:51 MDT 2018" 
          ports:
          - containerPort: 8080
            name: devices-port
