apiVersion: v1
kind: Service
metadata:
  name: api-template 
  labels:
    app: api-template 
spec:
  type: LoadBalancer
  loadBalancerIP: "35.230.49.200"
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80 
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443 
  selector:
    app: api-template