build:
	docker build  -t dockerowy/appa-micro-image-recognizer:dev . 

push:
	docker push dockerowy/appa-micro-image-recognizer:dev 

start:
	docker run -i -t dockerowy/appa-micro-image-recognizer:dev /bin/bash