apiVersion: v1
kind: Service
metadata:
  name: gorush
  labels:
    app: gorush
    tier: frontend
spec:
  selector:
    app: gorush
    tier: frontend
  ports:
  - protocol: TCP
    port: 9000 
    targetPort: 9000