# minikube storage class - standard is built in
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard 