apiVersion: v1
kind: Service
metadata:
  name: stories 
  labels:
    app: stories 
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5000 
    targetPort: 9000
    nodePort: 30010
  selector:
    app: stories 