// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/asciiu/appa/lib/user/models"
)

type Message struct {
	ID        string    `json:"id"`
	User      string    `json:"user"`
	CreatedAt time.Time `json:"createdAt"`
	Text      string    `json:"text"`
}

type Token struct {
	Jwt     *string `json:"jwt"`
	Refresh *string `json:"refresh"`
}

type TokenUser struct {
	User  *models.User `json:"user"`
	Token *Token       `json:"token"`
}
