apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service 
  template:
    metadata:
      labels:
        app: user-service 
    spec:
        containers:
        - name: user-service 
          image: us.gcr.io/fomo-204904/user-service:latest
          imagePullPolicy: Always
          command: [
            "./user-service",
            "--selector=static",
            "--server_address=:8080"
          ]
          envFrom:
          - configMapRef:
              name: fomo-config
          env:
          - name: UPDATED_AT
            value: "Mon 19 Mar 2018 12:05:58 GMT"
          ports:
          - containerPort: 5000
            name: users-port
