apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine 
  template:
    metadata:
      labels:
        app: engine 
    spec:
        containers:
        - name: execution-engine
          image: us.gcr.io/fomo-204904/execution-engine:latest
          imagePullPolicy: Always
          command: [
            "./execution-engine",
            "--selector=static",
            "--server_address=:8080",
          ]
          envFrom:
          - configMapRef:
              name: fomo-config
          env:
          - name: UPDATED_AT
            value: "Tue 20 Mar 2018 08:53:19 GMT"
          ports:
          - containerPort: 8080
            name: engine-port
