apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine 
  template:
    metadata:
      labels:
        app: engine 
    spec:
        containers:
        - name: execution-engine
          image: us.gcr.io/fomo-204904/execution-engine:latest
          imagePullPolicy: Always
          command: [
            "./execution-engine",
         		"--server_address=0.0.0.0:8080",
		        "--broker_address=0.0.0.0:10001"
          ]
          envFrom:
          - configMapRef:
              name: fomo-config
          env:
          - name: UPDATED_AT
            value: "Mon 19 Mar 2018 12:05:58 GMT"
          ports:
          - containerPort: 8080
            name: engine-port
