apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fomo-stage-vol
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: pvc-ace4ac9c-63aa-11e8-82b2-42010a8a0170