apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: binance 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance 
  template:
    metadata:
      labels:
        app: binance 
    spec:
        containers:
        - name: binance-service 
          image: us.gcr.io/fomo-204904/binance-service:latest
          imagePullPolicy: Always
          command: [
            "./binance-service",
            "--selector=static",
            "--server_address=:8080"
          ]
          envFrom:
          - configMapRef:
              name: fomo-config
          env:
          - name: UPDATED_AT
            value: "Mon 19 Mar 2018 12:05:58 GMT"
          ports:
          - containerPort: 8080
            name: binance-port
