// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/order/order.proto

/*
Package order is a generated protocol buffer package.

It is generated from these files:
	proto/order/order.proto

It has these top-level messages:
	OrderRequest
	UserOrdersRequest
	NewOrderRequest
	Order
	OrderData
	OrdersPage
	OrdersPageResponse
	OrderResponse
	StatusResponse
*/
package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OrderService service

type OrderService interface {
	AddOrder(ctx context.Context, in *NewOrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	CancelOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*StatusResponse, error)
	FindOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	FindUserOrders(ctx context.Context, in *UserOrdersRequest, opts ...client.CallOption) (*OrdersPageResponse, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "orderservice"
	}
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) AddOrder(ctx context.Context, in *NewOrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.AddOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) CancelOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*StatusResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.CancelOrder", in)
	out := new(StatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) FindOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.FindOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) FindUserOrders(ctx context.Context, in *UserOrdersRequest, opts ...client.CallOption) (*OrdersPageResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.FindUserOrders", in)
	out := new(OrdersPageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceHandler interface {
	AddOrder(context.Context, *NewOrderRequest, *OrderResponse) error
	CancelOrder(context.Context, *OrderRequest, *StatusResponse) error
	FindOrder(context.Context, *OrderRequest, *OrderResponse) error
	FindUserOrders(context.Context, *UserOrdersRequest, *OrdersPageResponse) error
}

func RegisterOrderServiceHandler(s server.Server, hdlr OrderServiceHandler, opts ...server.HandlerOption) error {
	type orderService interface {
		AddOrder(ctx context.Context, in *NewOrderRequest, out *OrderResponse) error
		CancelOrder(ctx context.Context, in *OrderRequest, out *StatusResponse) error
		FindOrder(ctx context.Context, in *OrderRequest, out *OrderResponse) error
		FindUserOrders(ctx context.Context, in *UserOrdersRequest, out *OrdersPageResponse) error
	}
	type OrderService struct {
		orderService
	}
	h := &orderServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderService{h}, opts...))
}

type orderServiceHandler struct {
	OrderServiceHandler
}

func (h *orderServiceHandler) AddOrder(ctx context.Context, in *NewOrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.AddOrder(ctx, in, out)
}

func (h *orderServiceHandler) CancelOrder(ctx context.Context, in *OrderRequest, out *StatusResponse) error {
	return h.OrderServiceHandler.CancelOrder(ctx, in, out)
}

func (h *orderServiceHandler) FindOrder(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.FindOrder(ctx, in, out)
}

func (h *orderServiceHandler) FindUserOrders(ctx context.Context, in *UserOrdersRequest, out *OrdersPageResponse) error {
	return h.OrderServiceHandler.FindUserOrders(ctx, in, out)
}
