// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Requests
type OrderRequest struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{0}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type NewOrderRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	MarketName           string   `protobuf:"bytes,2,opt,name=marketName,proto3" json:"marketName,omitempty"`
	Side                 string   `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	Size                 float64  `protobuf:"fixed64,4,opt,name=size,proto3" json:"size,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderRequest) Reset()         { *m = NewOrderRequest{} }
func (m *NewOrderRequest) String() string { return proto.CompactTextString(m) }
func (*NewOrderRequest) ProtoMessage()    {}
func (*NewOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{1}
}

func (m *NewOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderRequest.Unmarshal(m, b)
}
func (m *NewOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderRequest.Marshal(b, m, deterministic)
}
func (m *NewOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderRequest.Merge(m, src)
}
func (m *NewOrderRequest) XXX_Size() int {
	return xxx_messageInfo_NewOrderRequest.Size(m)
}
func (m *NewOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderRequest proto.InternalMessageInfo

func (m *NewOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *NewOrderRequest) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *NewOrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *NewOrderRequest) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *NewOrderRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// Responses
type Order struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	MarketName           string   `protobuf:"bytes,3,opt,name=marketName,proto3" json:"marketName,omitempty"`
	Side                 string   `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	Size                 float64  `protobuf:"fixed64,5,opt,name=size,proto3" json:"size,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedOn            string   `protobuf:"bytes,8,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	UpdatedOn            string   `protobuf:"bytes,9,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Order) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Order) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *Order) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Order) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Order) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Order) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

type OrderData struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderData) Reset()         { *m = OrderData{} }
func (m *OrderData) String() string { return proto.CompactTextString(m) }
func (*OrderData) ProtoMessage()    {}
func (*OrderData) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{3}
}

func (m *OrderData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderData.Unmarshal(m, b)
}
func (m *OrderData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderData.Marshal(b, m, deterministic)
}
func (m *OrderData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderData.Merge(m, src)
}
func (m *OrderData) XXX_Size() int {
	return xxx_messageInfo_OrderData.Size(m)
}
func (m *OrderData) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderData.DiscardUnknown(m)
}

var xxx_messageInfo_OrderData proto.InternalMessageInfo

func (m *OrderData) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderResponse struct {
	Status               string     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *OrderData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{4}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderResponse) GetData() *OrderData {
	if m != nil {
		return m.Data
	}
	return nil
}

type StatusResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{5}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderRequest)(nil), "OrderRequest")
	proto.RegisterType((*NewOrderRequest)(nil), "NewOrderRequest")
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*OrderData)(nil), "OrderData")
	proto.RegisterType((*OrderResponse)(nil), "OrderResponse")
	proto.RegisterType((*StatusResponse)(nil), "StatusResponse")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor_986e030a471601a2) }

var fileDescriptor_986e030a471601a2 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xe2, 0x30,
	0x10, 0x86, 0x31, 0x24, 0x81, 0x0c, 0x0b, 0xac, 0x7c, 0xd8, 0xb5, 0x56, 0x08, 0x21, 0x9f, 0x58,
	0x69, 0x65, 0x24, 0xf6, 0x09, 0xda, 0xa2, 0x4a, 0xbd, 0x80, 0x14, 0x9e, 0xc0, 0xc5, 0x56, 0x85,
	0x5a, 0x92, 0x34, 0x76, 0x5a, 0xb5, 0xf7, 0x3e, 0x46, 0x1f, 0xb0, 0x6f, 0x51, 0x65, 0x1c, 0x20,
	0x69, 0xa1, 0x87, 0x5e, 0xa2, 0x99, 0xff, 0x9f, 0x78, 0xbe, 0xc9, 0x38, 0xf0, 0x3b, 0xcd, 0x12,
	0x9b, 0x4c, 0x93, 0x4c, 0xe9, 0xcc, 0x3d, 0x05, 0x2a, 0x7c, 0x02, 0x3f, 0x96, 0x45, 0x1a, 0xe9,
	0xfb, 0x5c, 0x1b, 0x4b, 0x19, 0xb4, 0xd1, 0xbe, 0x9a, 0x33, 0x32, 0x26, 0x93, 0x30, 0xda, 0xa5,
	0xfc, 0x85, 0xc0, 0x60, 0xa1, 0x1f, 0x6b, 0xd5, 0xbf, 0x20, 0xc8, 0x4d, 0xa5, 0xb8, 0xcc, 0xe8,
	0x08, 0x60, 0x2b, 0xb3, 0x5b, 0x6d, 0x17, 0x72, 0xab, 0x59, 0x13, 0xbd, 0x8a, 0x42, 0x29, 0x78,
	0x66, 0xa3, 0x34, 0x6b, 0xa1, 0x83, 0xb1, 0xd3, 0x9e, 0x35, 0xf3, 0xc6, 0x64, 0x42, 0x22, 0x8c,
	0x0b, 0xcd, 0x3e, 0xa5, 0x9a, 0xf9, 0xae, 0xae, 0x88, 0xf9, 0x1b, 0x01, 0x1f, 0x21, 0x4e, 0xb3,
	0x56, 0xb8, 0x9a, 0x5f, 0x70, 0xb5, 0x4e, 0x72, 0x79, 0x47, 0xb8, 0xfc, 0x23, 0x5c, 0xc1, 0x81,
	0xab, 0xe8, 0x69, 0xac, 0xb4, 0xb9, 0x61, 0x6d, 0xd7, 0xd3, 0x65, 0x74, 0x08, 0xe1, 0x3a, 0xd3,
	0xd2, 0x6a, 0xb5, 0x8c, 0x59, 0x07, 0xad, 0x83, 0x50, 0xb8, 0x79, 0xaa, 0x4a, 0x37, 0x74, 0xee,
	0x5e, 0xe0, 0x7f, 0x21, 0xc4, 0x51, 0xe7, 0xd2, 0x4a, 0x3a, 0x04, 0x1f, 0xe7, 0xc3, 0x61, 0xbb,
	0xb3, 0x40, 0xb8, 0x55, 0x38, 0x91, 0x4b, 0xe8, 0x95, 0xab, 0x31, 0x69, 0x12, 0x9b, 0x2a, 0x0f,
	0xa9, 0xf1, 0x30, 0x68, 0x6f, 0xb5, 0x31, 0xf2, 0x66, 0xb7, 0x98, 0x5d, 0x4a, 0x47, 0xe0, 0x29,
	0x69, 0x25, 0x7e, 0x97, 0xee, 0x0c, 0xc4, 0xbe, 0x75, 0x84, 0x3a, 0x3f, 0x87, 0xfe, 0x0a, 0xcf,
	0xf8, 0x7e, 0x8f, 0xd9, 0x2b, 0x29, 0x2f, 0xdc, 0x4a, 0x67, 0x0f, 0x9b, 0xb5, 0xa6, 0x02, 0x3a,
	0x67, 0x4a, 0xb9, 0x85, 0xfe, 0x14, 0x1f, 0x2e, 0xd8, 0x9f, 0xbe, 0xa8, 0x0d, 0xc5, 0x1b, 0x74,
	0x0a, 0xdd, 0x0b, 0x19, 0xaf, 0xf5, 0x9d, 0x7b, 0xa5, 0x27, 0x6a, 0xf5, 0x03, 0x51, 0x27, 0xe4,
	0x0d, 0xfa, 0x0f, 0xc2, 0xcb, 0x4d, 0xac, 0x8e, 0x96, 0x7f, 0x3a, 0xfe, 0x3a, 0xc0, 0xdf, 0xe2,
	0xff, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x23, 0x43, 0xbf, 0x31, 0x03, 0x00, 0x00,
}
