apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: analytics 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics 
  template:
    metadata:
      labels:
        app: analytics 
    spec:
        containers:
        - name: analytics-service 
          image: us.gcr.io/fomo-204904/analytics-service:dev
          imagePullPolicy: Always 
          command: [
            "./analytics-service",
            "--selector=static",
            "--server_address=:8080"
          ]
          envFrom:
          - configMapRef:
              name: fomo-config
          env:
          - name: UPDATED_AT
            value: "Mon Aug 27 18:31:57 MDT 2018" 
          ports:
          - containerPort: 8080
            name: analytics-port
